name: Docker Image CI

on:
  push:
    branches:
      - master
    paths:
      - 'node/*'
jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Login
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login docker.pkg.github.com -u superbarne -p $GITHUB_TOKEN
    - name: Build the Docker image
      run: cd node && docker build . --file Dockerfile --tag docker.pkg.github.com/superbarne/docker-tools/node:$(date +%s)
