name: Docker Image CI

on:
  push:
    branches:
      - master
    paths:
      - 'node/*'
jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: cd node && docker build . --file Dockerfile --tag barne/node:$(date +%s)
